# configuration template for myaudit

[parm]
# MyBatis xml文件名
Filename = "test.xml"
# 数据库用户，只需最基本的usage权限，无需任何额外权限，实际运行时可将root换为任意用户
Username = "root"
# 数据库用户密码
Password = "123456"
# 非线上环境数据库连接串
TestDSN = "192.168.153.130:3306/sakila"

[path]
# 根路径用于存放myaudit解析生成的各类文件和项目依赖，需确保根路径存在且具备读写权限
PathRoot = "/usr/local/myaudit"
